[package]
name = "patapon3-enc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camellia-rs = "0.2.0"
clap = "3.2.18"
indicatif = "0.17.3"
